export { default as BottomBarComponent } from './BottomBarComponent.vue'
export { default as ChatComponent } from './ChatComponent.vue'
export { default as NavbarComponent } from './NavbarComponent.vue'
export { default as TopBarComponent } from './TopBarComponent.vue'
export { default as SideBarComponent } from './SideBarComponent.vue'
